name: pandera-blog
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - altair
  - ipykernel
  - jupyter
  - jupyterlab
  - jupytext
  - pandas >= 1.0.0
  - pandera >= 0.6.0
  - matplotlib
  - seaborn
  - scikit-learn
